#!/usr/bin/env sh
# # https://github.com/docker/hub-feedback/issues/508#issuecomment-240616319
# Usage :
#   $0 <dockerfile-target> <final-image-tag>
#
# must be imported from inside eachy ./<image-folder>/hook/build script
build()
{
  echo "------ HOOK START - BUILD -------"
  export $(cat ../../.env | xargs)
  export COMPOSE_FILE=../../docker-compose.yaml target=$1 IMMUTABLE_TAG=$2;
  export IMMUTABLE_IMAGE_NAME=${DOCKER_REPO}:${IMMUTABLE_TAG} IMAGE_NAME_ONLY=$(echo $DOCKER_REPO | cut -d"/" -f3)
  export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  docker-compose build builder;
  docker tag ${IMMUTABLE_IMAGE_NAME} ${IMAGE_NAME}

  echo "---publish immutable artifact ----"
  docker push ${IMMUTABLE_IMAGE_NAME}
  echo "------ HOOK END - BUILD -------"
}


# NOTE
# DOCKER_REPO=index.docker.io/abdennour/envsubt
# IMAGE_NAME=index.docker.io/abdennour/envsubt:latest