#!/usr/bin/env sh
# # https://github.com/docker/hub-feedback/issues/508#issuecomment-240616319
# Usage :
#   $0 <dockerfile-target> <final-image-tag>
#
# must be imported from inside eachy ./<image-folder>/hook/build script
export $(cat ../../.env | xargs)
cp ../../docker-compose.yaml .
cp ../../.env .
export IMAGE_NAME_ONLY=$(echo $DOCKER_REPO | cut -d"/" -f3)

lint_function()
{
  docker run --rm -i hadolint/hadolint hadolint --ignore DL3018 $@ - < Dockerfile
}

build_function()
{
  echo "------ HOOK START - BUILD -------"
  export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` target=$1 IMMUTABLE_TAG=$2
  export IMMUTABLE_IMAGE_NAME=${DOCKER_REPO}:${IMMUTABLE_TAG}
  echo '--- Env vars just before building'
  printenv
  docker-compose build builder;
  # functional test
  test_function ${IMMUTABLE_IMAGE_NAME}
  # release
  docker tag ${IMMUTABLE_IMAGE_NAME} ${IMAGE_NAME}

  echo "---publish immutable artifact ----"
  docker push ${IMMUTABLE_IMAGE_NAME}
  echo "------ HOOK END - BUILD -------"
}

build_from_external_git()
{
  repo_url=$1
  tag_or_branch=$2
  repo_basename=$(basename ${repo_url} .git)
  tmp_dir=/tmp/external-builds
  mkdir -p ${tmp_dir}
  echo "cloning ${repo_url} into ${tmp_dir}"
  git -C ${tmp_dir} clone --depth 1 \
          --branch ${tag_or_branch} \
          ${repo_url}
  docker build -t tmp:${tag_or_branch} ${tmp_dir}/${repo_basename}
}

test_function()
{
  if [ -f "specs.yaml" ]; then
    docker-compose run --rm container-structure-test test \
      --image ${image_name} --config specs.yaml
  else
    echo "WARNING: no contrainer structure tests to run"
    echo "INFO: please write tests in docker-images/${IMAGE_NAME_ONLY}/specs.yaml file"
  fi

}

# NOTE
# DOCKER_REPO=index.docker.io/abdennour/envsubt
# IMAGE_NAME=index.docker.io/abdennour/envsubt:latest