#!/usr/bin/env sh
# https://github.com/docker/hub-feedback/issues/508#issuecomment-240616319

echo "------ HOOK START - BUILD -------"
ls -la
echo '----------ls -la ..'
ls -la ../
pwd
export $(cat ../../.env | xargs)
IMAGE_NAME=$(echo -n $IMAGE_NAME | sed 's/latest/'${AWS_CLI_VERSION}'/g');

printenv


docker build \
  --build-arg AWS_CLI_VERSION=${AWS_CLI_VERSION} \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=$SOURCE_COMMIT -t ${DOCKER_REPO}:${AWS_CLI_VERSION} .

docker tag ${DOCKER_REPO}:${AWS_CLI_VERSION} ${IMAGE_NAME}

# export IMAGE_NAME=${DOCKER_REPO}:${AWS_CLI_VERSION}
echo "------ HOOK END - BUILD -------"


# NOTE
# DOCKER_REPO=index.docker.io/abdennour/aws
# IMAGE_NAME=index.docker.io/abdennour/aws:latest
