#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)

build_function docker ${DOCKER_VERSION}-dind

build_function docker-buildx ${DOCKER_VERSION}-buildx-${BUILDX_VERSION}

build_function docker-compose ${DOCKER_VERSION}-compose-${DOCKER_COMPOSE_VERSION}
build_function docker-compose-ssl ${DOCKER_VERSION}-compose-${DOCKER_COMPOSE_VERSION}-ssl
build_function docker-compose-ssh ${DOCKER_VERSION}-compose-${DOCKER_COMPOSE_VERSION}-ssh
build_function docker-compose-ssh-ssl ${DOCKER_VERSION}-compose-${DOCKER_COMPOSE_VERSION}-ssh-ssl

build_function docker-aws ${DOCKER_VERSION}-dind-aws${AWS_CLI_VERSION}
build_function docker-compose-v1 ${DOCKER_VERSION}-dind-compose${DOCKER_COMPOSE_VERSION_V1}
build_function docker-compose-aws ${DOCKER_VERSION}-dind-compose${DOCKER_COMPOSE_VERSION_V1}-aws${AWS_CLI_VERSION}

# build_function     target           tag

