#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)

build_function docker ${DOCKER_VERSION}-dind
build_function docker-aws ${DOCKER_VERSION}-dind-aws${AWS_CLI_VERSION}
build_function docker-compose ${DOCKER_VERSION}-dind-compose${DOCKER_COMPOSE_VERSION}
build_function docker-compose-aws ${DOCKER_VERSION}-dind-compose${DOCKER_COMPOSE_VERSION}-aws${AWS_CLI_VERSION}

# build_function     target           tag

