#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)
build_function eksctl ${EKSCTL_VERSION}-aws-${AWS_CLI_VERSION}
build_function eksctl-kubectl ${EKSCTL_VERSION}-aws-${AWS_CLI_VERSION}-kubectl-${KUBECTL_VERSION}
# build    target             tag