#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)


build_function ubuntu-desktop-devtools ${UBUNTU_DESKTOP_VERSION}-devtools-$(echo $SOURCE_COMMIT| cut -c1-4)

# build    target             tag