#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)

if [ ! -z "${SOURCE_COMMIT}" ]; then
  export COMMIT_ID_SHORT=v$(echo $SOURCE_COMMIT | tail -c +2|head -c 3)
else
  timestamp=v$(date +%s)
  export COMMIT_ID_SHORT=v$(echo $timestamp | tail -c +2|head -c 3)
fi
build_function rhel7 7
build_function rhel7-ssh 7-ssh
build_function rhel7-ssh 7-ssh-${COMMIT_ID_SHORT}
build_function rhel8 8
build_function rhel8 8-${COMMIT_ID_SHORT}
build_function rhel8-ssh 8-ssh
build_function rhel8-ssh 8-ssh-${COMMIT_ID_SHORT}
# build    target             tag