#!/bin/bash


if [ -n "$DOCKER_GID_ON_HOST" ]; then

  echo "Create group for docker with gid $DOCKER_GID_ON_HOST"
  sudo groupadd -g $DOCKER_GID_ON_HOST docker && sudo grpconv
  sudo usermod -a  -G $DOCKER_GID_ON_HOST user
  dockerGroupName=$(cat /etc/group | grep :$DOCKER_GID_ON_HOST: | cut -d: -f1)

fi;

if [ -n "${EXTRA_PATH}" ]; then
  export PATH=${EXTRA_PATH}:${PATH}

fi;

if [ "${SUDO_FORCE_REMOVE}" = "yes" ]; then
  # sudo apt-get remove --purge sudo -y
  sudo sed -i '/user\ ALL/d' /etc/sudoers
fi

baseEntryPoint=$(/dockerstartup/vnc_startup.sh "$@")	
if [ -n "$dockerGroupName" ]; then 
  exec sg $dockerGroupName "$baseEntryPoint"
else
  exec $baseEntryPoint
fi