#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)
if [ ! -z "${SOURCE_COMMIT}" ]; then
  export COMMIT_ID_SHORT=v$(echo $SOURCE_COMMIT | tail -c +2|head -c 3)
else
  timestamp=v$(date +%s)
  export COMMIT_ID_SHORT=v$(echo $timestamp | tail -c +2|head -c 3)
fi

build_function radius-auth-proxy ${HTTPD_VERSION}-alpine
build_function radius-auth-proxy ${HTTPD_VERSION}-alpine-${COMMIT_ID_SHORT}
# build    target             tag