#!/usr/bin/env sh
. ../../pipeline_functions

export $(cat ../../.env | xargs)
export COMMIT_ID_SHORT=${SOURCE_COMMIT:0:3}

build_function radius-auth-proxy ${HTTPD_VERSION}-alpine
build_function radius-auth-proxy ${HTTPD_VERSION}-alpine-${COMMIT_ID_SHORT}
# build    target             tag