#!/usr/bin/env sh
. ../../build_function

echo "which build_function ----------------"
which build_function;

build_function alpine-perl alpine-${ALPINE_VERSION}-perl
# build    target             tag