#!/usr/bin/env sh
. ../../pipeline_functions
echo "ls -l ---- LOG ---------------------"
ls -la
export $(cat ../../.env | xargs)
build_function alpine-perl alpine-${ALPINE_VERSION}-perl
# build    target             tag